vim.keymap.set({'n', 'v'}, '<C-j>', '10j', {noremap = true, silent = true})
vim.keymap.set({'n', 'v'}, '<C-k>', '10k', {noremap = true, silent = true})
vim.keymap.set({'n'}, ',,', '<cmd>Explore<CR>', {noremap = true, silent = true})
vim.keymap.set({'n', 'v'}, '<leader>jj', '<cmd>bnext<CR>', {noremap = true, silent = true})
vim.keymap.set({'n', 'v'}, '<leader>kk', '<cmd>bprev<CR>', {noremap = true, silent = true})
vim.keymap.set({'n'}, '<leader>o', '<cmd>only<CR>', {noremap = true, silent = true})
vim.keymap.set({'n'}, '<leader>d', '<cmd>bd<CR>', {noremap = true, silent = true})
vim.keymap.set({'n'}, '<leader>bn', '<cmd>enew<CR>', {noremap = true, silent = true})
vim.keymap.set({'n'}, '<leader>qq', '<cmd>qa!<CR>', {noremap = true, silent = true})
vim.keymap.set({'n'}, '<C-a>', 'gg0vG$', {noremap = true, silent = true})
vim.keymap.set({'n', 'i'}, '<C-s>', '<ESC><cmd>w<CR>', {noremap = true, silent = true})
vim.keymap.set({'n'}, 'gU', 'vawgU', {noremap = true, silent = true})
vim.keymap.set({'n'}, 'gu', 'vawgu', {noremap = true, silent = true})
vim.keymap.set({'n', 'i'}, '<C-t>', '<cmd>term<CR>', {noremap = true, silent = true})
vim.keymap.set({'t'}, '<ESC>', '<C-\\><C-n>', {noremap = true, silent = true})
